#!/bin/bash

# VERSION OF CCM+ TO RUN
###############################################################################
export CCM_HOME="/raid/linux8/apps/starccm/14.02.012-R8/STAR-CCM+14.02.012-R8/"

CCM_EXEC="${CCM_HOME}/star/bin/starccm+"

# SET OPTIONS
###############################################################################
#MACHINES="linux21:2,linux22:2,linux4:2,linux3:2"
#MACHINES="linux21:1,linux22:1"
#MACHINES="linux21:40,linux22:40"
#MACHINES="linux4:60,linux3:60"
#MACHINES="linux4:60"
MACHINES="linux16:12"
#MACHINES="linux4:60,linux3:60,linux22:44,linux21:44"
#MACHINES="linux4:60,linux3:60,linux40:60,linux22:44,linux21:44"

## WORKING DIR ##
###############################################################################
# In vim, go to empty line under WD=... and type " !!pwd " to print working directory
# then type @c to comment out line above and prepend WD=...

#WD="/raid/linux4/flyntga/0_95957_Navy_TF/tmc6/inviscid"
#WD="/raid/linux4/flyntga/0_95957_Navy_TF/tmc6/inviscid/6b"
WD="/home/flyntga/git/optuna"

## SIM FILE ##
###############################################################################
# In vim, go to empty line under SIMFILE and type " !!ls *sim " to print sim files
# then type @c to comment out line above and prepend SIMFILE=...

#SIMFILE="tmc6_inviscid@02861.sim"
#SIMFILE="tmc6br.sim"
#SIMFILE="tmc6bf.sim"
SIMFILE="ncTref.sim"

## LICENSE ##
###############################################################################
#POWER="-power -podkey VQpHwX/R93hhAWZIfUICeQ -mpi platform -cpubind -licpath 1999@flex.cd-adapco.com"
#POWER="-power -mpi platform -cpubind -licpath 1999@flex.cd-adapco.com"
#POWER="-power -mpi intel -cpubind -licpath 1999@flex.cd-adapco.com"
#POWER="-power -mpi intel"
POWER="-power -podkey KhqnxnyyHstD7KSWi1dn4g  -mpi intel -cpubind -licpath 1999@flex.cd-adapco.com"

RSH="-rsh ssh "

echo "Running $SIMFILE"
#echo "OPENMPI_DIR = $OPENMPI_DIR"


MACROF="setgeom_mesh_run.java"

# CALL CCM+
###############################################################################
#$CCM $POWER -batch mesh,run -on $MACHINES $WD/$SIMFILE
#$CCM $POWER -batch -on $MACHINES $WD/$SIMFILE
#$CCM_EXEC $POWER -batch -on $MACHINES $RSH $WD/$SIMFILE
$CCM_EXEC $POWER -batch $MACROF -on $MACHINES $RSH $WD/$SIMFILE
